SnsTemplate provides functionality to validate topic existence (#1137)
awspring/spring-cloud-aws pull request #1142
Opened 2024-04-28 08:13 UTC by hardikSinghBehl

## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Implemented the method `boolean topicExists(String topicArn)` in `SnsTemplate` to validate the existence of an SNS topic via an ARN.

## :bulb: Motivation and Context

Implementation for issue #1137

## :green_heart: How did you test it?
The functionality has been tested by writing integration tests for the new method. 

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

2024-04-30 15:59 UTC, MatejNedic commented
Hey @hardikSinghBehl thanks on PR! Will take a deeper look tomorrow and come back to you

2024-05-01 06:32 UTC, MatejNedic requested changes
All good, just remove that 1 thing from gitignore

2024-05-01 06:32 UTC, MatejNedic commented on .gitignore
> +.DS_Store
Please remove this

2024-05-01 06:48 UTC, hardikSinghBehl commented
done, @MatejNedic

2024-05-01 06:55 UTC, MatejNedic approved these changes

2024-09-18 13:10 UTC, merged

2024-09-18 13:10 UTC, maciejwalkowiak commented
Thanks @hardikSinghBehl!