Verify sns message signature
awspring/spring-cloud-aws pull request #198
Opened 2021-11-02 16:14 UTC by WtfJoke

Fixes gh-176

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Verify the signature of a SNS Message by utilizing [SnsMessageManager#parseMessage](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sns/message/SnsMessageManager.html#parseMessage-java.io.InputStream-) which also validates the Signature using SignatureVerifier. The downside of it, it does more than just validate the Signature, but I think it doesnt hurt.

As an alternative we could also validate the Signature using [SignatureChecker (aws sdk v1)](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sns/util/SignatureChecker.html), but the class is deprecated and they suggest using SnsMessageManager.

In aws sdk 2 there would be a more optimal approach using [SignatureChecker (aws sdk v2)](https://github.com/aws/aws-sdk-java-v2/blob/master/services/sns/src/it/java/software/amazon/awssdk/services/sns/SignatureChecker.java#L40), but we still have aws sdk 1 here.

## :bulb: Motivation and Context

#176

## :green_heart: How did you test it?
I'll added two junit tests, which tests two cases (invalid/valid signature). 
For that I needed to add an additional constructor in order to be able to mock SnsMessageManager. I hope thats ok. 

I also verified it, by publishing some messages in my sns topic through the aws management console.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

2021-12-14 12:01 UTC, maciejwalkowiak approved these changes
Thanks! We will include it in 2.4

2021-12-16 07:18 UTC, MatejNedic requested changes
@WtfJoke thanks for contribution!
I have an issue that we should address to have PR ready for Merge

2022-01-13 23:38 UTC, WtfJoke commented
Just wanted to let you know that I will soon take care of the requested changes.

2022-01-16 13:13 UTC, WtfJoke commented on spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/support/converter/NotificationRequestConverter.java
> +	private final SnsMessageManager snsMessageManager;
@maciejwalkowiak First of nice find.

I know its been a while, but I dont understand the recommended approach fully 😅.  `SnsMessageManager` has the default constructor (which uses the wrong region) and the one where I pass the region. So I should use that one. 

How and where can I inject the correct region? I suppose I shouldnt duplicate the code in the `SnsAutoConfiguration`, right? Or should I simply inject `SNSProperties` and use this region (but which region provider do I use if the property is null, the default one)?

2022-01-18 19:20 UTC, MatejNedic commented on spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/support/converter/NotificationRequestConverter.java
> +	private final SnsMessageManager snsMessageManager;
Personally, I would create `SnsMessageManager` bean in `SnsAutoConfiguration` and pass it to `NotificationRequestConverter`.
For a region use `regionProvider` located in `SnsAutoConfiguration`.

@maciejwalkowiak @eddumelendez WDYT? Could you assist further?

2022-01-29 15:43 UTC, WtfJoke commented on spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/support/converter/NotificationRequestConverter.java
> +	private final SnsMessageManager snsMessageManager;
Your explaination helped, thank you. I pushed the changes. 

I always struggle a bit with formatting issues 😅 I've only managed to do this on my linux machine.
Havent yet tested the changes, but I think you still can take a look at it.

2022-01-29 16:19 UTC, WtfJoke commented on spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/support/converter/NotificationRequestConverter.java
> +	private final SnsMessageManager snsMessageManager;
Strangely enough, all tests are green on my machine :S

2022-02-05 17:53 UTC, maciejwalkowiak requested changes
I've had another look and I think we approached in from a wrong side. 

Signature verification should happen for messages sent to an HTTP endpoint, not ones sent to SQS queue. This means, we do not need to verify signature in `QueueMessageHandler` but rather somewhere in `NotificationMessageHandlerMethodArgumentResolver`. SQS related code should ideally not need to change. 

I know it's been a while, so is this something @WtfJoke you would be still interested in doing?

2022-02-08 19:22 UTC, WtfJoke commented
@maciejwalkowiak no worries, I know the struggle of the life of a maintainer :D

However currently im quite occupied, so I dont want to block anybody which is interested in doing that.  Feel free to close the PR.

Thank you both for taking a look to the PR in the past.

2022-02-08 19:22 UTC, closed without merging