SNS sample
awspring/spring-cloud-aws pull request #25
Opened 2021-01-22 18:50 UTC by MatejNedic

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
CDK  and Spring boot application that shows Spring cloud aws SNS integration.

## :bulb: Motivation and Context
Currently there is no sample for SNS.

## :green_heart: How did you test it?

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

2021-01-25 17:38 UTC, maciejwalkowiak requested changes
Sending SNS message is one thing, Ideally we also show how to receive SNS messages with `@NotificationMapping`.

2021-01-25 17:38 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/infrastracture/README.md
> +
Since it's a markdown the IAM policy should be formatted with backticks https://www.markdownguide.org/basic-syntax/#code-blocks

2021-01-25 17:38 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/infrastracture/lib/infrastracture-stack.ts
> +      displayName: 'Spring cloud AWS SNS samplenpm i @aws-cdk/aws-sns',
Display name does not seem valid

2021-01-25 17:38 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/infrastracture/README.md
> +Infrastructure code to run **Spring Cloud AWS SNS Sample App** based on [AWS CDK](https://aws.amazon.com/cdk/)
Ideally we should explain what does this sample do.

2021-02-17 19:24 UTC, maciejwalkowiak commented
@MatejNedic are you working still on this one? Ideally this should show to use `@NotificationMapping`

2021-02-19 11:49 UTC, maciejwalkowiak requested changes
Just small bits to change. Thanks Matej!

2021-02-19 11:49 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/infrastracture/README.md
> +                 "sns:ListTopics",
formatting here isn't right

2021-02-19 11:49 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/pom.xml
> +		<dependency>
Do we need both `spring-boot-starter-web` and `spring-webmvc` dependencies? Starter brings already Spring MVC but it also brings much more stuff - is it possible to not include the starter?

2021-02-19 11:49 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/pom.xml
> +		<dependency>
formatting isn't right

2021-02-19 11:49 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/infrastracture/README.md
> +There is possibility subscription isn't confirmed since application is not started as of CDK deploy, so you should resend subscription from a console.
"console" can be understood as a terminal or AWS console. Maybe we can be more precise here and give step by step instructions how to do it?

2021-03-01 21:55 UTC, maciejwalkowiak requested changes
Thanks Matej! Great job. Tiny details to polish (I know I am picky here), if you don't want to do it I can polish them during merge.

2021-03-01 21:55 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/src/main/java/io/awspring/cloud/sns/sample/NotificationMappingController.java
> +			LOGGER.info("NotificationMessageMapping message is: " + message);
`LOGGER.info("NotificationMessageMapping message is: {}", message);` and same for other one

2021-03-01 21:55 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/src/main/java/io/awspring/cloud/sns/sample/SpringSNSSample.java
> +				MessageBuilder.withPayload("Spring cloud Aws SNS sample!").build());
"Spring cloud Aws SNS sample!" -> "Spring Cloud AWS SNS Sample!"

2021-03-01 21:55 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/src/main/java/io/awspring/cloud/sns/sample/NotificationMappingController.java
> +	@NotificationSubscriptionMapping
Empty line

2021-03-01 21:55 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/src/main/java/io/awspring/cloud/sns/sample/NotificationMappingController.java
> +
Remove empty line

2021-03-01 21:55 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/pom.xml
> +    <dependencies>
Add empty line above, remove empty line below.

2021-03-01 21:55 UTC, maciejwalkowiak commented on spring-cloud-aws-samples/spring-cloud-aws-sns-sample/pom.xml
> +
Remove empty lines.

2021-03-02 18:11 UTC, MatejNedic commented
@maciejwalkowiak Taken care of comments!

2021-03-10 21:52 UTC, maciejwalkowiak approved these changes

2021-03-11 01:57 UTC, eddumelendez approved these changes

2021-03-11 09:27 UTC, merged