Read bucket region from redirect header
awspring/spring-cloud-aws pull request #453
Opened 2022-07-11 20:11 UTC by fjmacagno

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
Read the bucket region from the PermanentRedirect error message headers and cache a client for that region. 

Unfortunately this was not doable with the LruCache, since it does not permit manual insertion of entries. If there is a better way i am happy to alter the impl.

## :bulb: Motivation and Context
Fixes #452 

## :green_heart: How did you test it?
Running with local project using bucket in region without owner access.

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2022-07-15 13:27 UTC, maciejwalkowiak requested changes
As much as I'd like to keep it simple with plain `ConcurrentHashMap`, we should not let this map grow infinitely. 

Please take a look at the `ConcurrentLruMap` in https://github.com/awspring/spring-cloud-aws/pull/456. Once it's merged I think you'll be able to finish this PR

2022-07-15 13:27 UTC, maciejwalkowiak commented on spring-cloud-aws-s3-parent/spring-cloud-aws-s3-cross-region-client/src/main/java/io/awspring/cloud/s3/crossregion/CrossRegionS3Client.java
> +				return fn.apply(bucketCache.computeIfAbsent(bucket, this::discoverBucketClient));
Since we can get this information from a header, I think we don't need `discoverBucketClient` any longer?

2022-07-22 18:31 UTC, fjmacagno commented
@maciejwalkowiak Unfortunately the ConcurrentLRUMap class is needed both by the spring-cloud-aws-s3-codegen and spring-cloud-aws-s3-cross-region-client projects in order to compile. How would you like to fix the project structure so this will work?

2022-08-03 06:28 UTC, maciejwalkowiak commented on spring-cloud-aws-s3-parent/spring-cloud-aws-s3-cross-region-client/src/main/java/io/awspring/cloud/s3/crossregion/CrossRegionS3Client.java
> +				return fn.apply(bucketCache.computeIfAbsent(bucket, this::discoverBucketClient));
You're right, there is no guarantee that header is there https://github.com/aws/aws-sdk-java/blob/fd409dee8ae23fb8953e0bb4dbde65536a7e0514/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/Headers.java#L226

2022-08-03 06:41 UTC, maciejwalkowiak commented
@fjmacagno can you bring back fallback when header is not present?

2022-08-09 18:03 UTC, fjmacagno commented
@maciejwalkowiak Have you considered getting rid of the autogen functionality? It is making what i am trying to do harder (since some client operations behave differently than others), and that combined with having to inline ConcurrentLruMap seems to suggest that it has outlived its usefulness.

2022-08-09 22:19 UTC, maciejwalkowiak commented
Client generation was meant to make things easier - and it did for me when creating initial cross client implementation. What is the problem you're facing?

2022-08-09 22:47 UTC, fjmacagno commented
Well, since we know that the header will be present for certain client operations, we could make the assumption that HeadObject and ListObject operations will always have the header, and throw an error otherwise.
Then, if the operation being done is anything else, and the 301 error occurs and the header isnt present, we could just call HeadObject on the bucket in use. If it returns successfully, we know that it was able to retrieve the region and cache the client, and we can continue.
This way, we can still avoid explicitly doing the annoying GetBucketLocation operation which only bucket owners can do.

The complexity here is that in order to avoid infinite recursion, those special operations need to not call themselves on an error. The methods i see currently are:
1. add a flag to `executeInBucketRegion` controlling the recursive call, defaulting to true and being false when called recursively
2. duplicate the error-code checking and header-retrieval logic into another method that just handles the HeadObject part

Both of these solutions though could result in a duplicate head or list operation being called, since we cant tell what operation the passed function is. If the client code wasnt generated, we could have the head and list operations call a simplified version of `executeInBucketRegion` which does not have the recursive logic, or even just pass a false flag from option 1, and so surface an exception faster.

A compromise option might be to have the code generation instead create an interface or abstract class with default methods for each of the S3Client methods, which would call the abstract method `executeInBucketRegion`. Then, the actual implementation could have overrides of specific S3Client methods (the HeadObject and ListObjects operations). This would also eliminate one of the mvn projects, and in principle the code generation could be an earlier maven step and not have to have the result committed, especially since the generated code would never change.

This is definitely not at all necessary, but i noticed what i was writing didn't feel right and i thought i would bring it up. i definitely may also be missing something obvious. I'll try to get one of simple options written as a reference.

2022-08-10 10:37 UTC, maciejwalkowiak commented
> A compromise option might be to have the code generation instead create an interface or abstract class with default methods for each of the S3Client methods, which would call the abstract method executeInBucketRegion. Then, the actual implementation could have overrides of specific S3Client methods (the HeadBucket and ListObjects operations). This would also eliminate one of the mvn projects, and in principle the code generation could be an earlier maven step and not have to have the result committed, especially since the generated code would never change.

This sounds like a good way to go. Feel free to go this path and when I am back from holidays I'll dig deeper. 

Thanks a lot for for analysis!

2022-08-11 17:17 UTC, maciejwalkowiak commented
@fjmacagno great job thanks a lot! I did tiny polishing with reducing the surface area of public APIs. 

One thing left that I think we should do but want to consult with you before - wouldn't renaming `CrossRegionS3Client` to `AbstractCrossRegionS3Client` and `DefaultCrossRegionS3Client` to `CrossRegionS3Client` make more sense? From the user point of view I think having `DefaultCrossRegionS3Client` may suggest like there are possibilities for other implementations and I don't think it is true in the scope of Spring Cloud AWS at least.

2022-08-11 17:52 UTC, fjmacagno commented
Thanks!

I just always leave the possibility open out of habit, especially when working with Spring, just to leave things flexible; i would argue a user should just be concerned with having an instance of the abstract class, and the library can do the details behind the scenes. I'm happy to do this however you would prefer though.

2022-08-11 19:45 UTC, fjmacagno commented
I made one more set of simplification changes. I could also fully get rid of the CrossRegionS3ClientTemplate if desired and just fully generate the class, but i dont know if that is a net-positive.

This is the cleanest i think i can make it without changing project structure.

2022-08-11 19:56 UTC, maciejwalkowiak commented
> especially when working with Spring, just to leave things flexible

That's true, Spring is very flexible, but we cannot afford such flexibility. For us hiding more means less effort to maintain it later (which is quite important for a side project).

>  i would argue a user should just be concerned with having an instance of the abstract class, and the library can do the details behind the scenes.

Users should ideally use `S3Client` interface.

I think it's good as it is - except naming, but I'll leave it open till @MatejNedic is back from holidays only to agree on naming.

2022-08-11 21:08 UTC, fjmacagno commented
Makes sense to me, i've renamed the classes.

2022-08-11 21:09 UTC, fjmacagno commented
If you change your mind, i am happy to revert.

2022-08-12 19:05 UTC, fjmacagno commented
I tried out some project changes in https://github.com/fjmacagno/spring-cloud-aws/pull/1 .

2022-08-15 18:01 UTC, MatejNedic requested changes
Hey, naming looks good except for one name.

2022-08-21 05:59 UTC, maciejwalkowiak commented on spring-cloud-aws-s3-parent/spring-cloud-aws-s3-codegen/src/main/java/io/awspring/cloud/s3/codegen/AbstractCrossRegionS3ClientGenerator.java
> +public final class AbstractCrossRegionS3ClientGenerator {
In this case it makes sense as it generates "AbstractCrossRegionS3Client" class.

2022-08-21 06:04 UTC, MatejNedic commented on spring-cloud-aws-s3-parent/spring-cloud-aws-s3-codegen/src/main/java/io/awspring/cloud/s3/codegen/AbstractCrossRegionS3ClientGenerator.java
> +public final class AbstractCrossRegionS3ClientGenerator {
I am still of a opinion that name is missleading. I understand it generates abstract class. What about "CrossRegionAbstractS3ClientGenrator"?  This makes sense to me more.

2022-08-21 06:13 UTC, merged

2022-08-21 06:18 UTC, maciejwalkowiak commented on spring-cloud-aws-s3-parent/spring-cloud-aws-s3-codegen/src/main/java/io/awspring/cloud/s3/codegen/AbstractCrossRegionS3ClientGenerator.java
> +public final class AbstractCrossRegionS3ClientGenerator {
Then it does not match the actual generated class name. Anyways, this class is not a part of our API so no user will be confused.