Use SqsTemplate instead of raw SqsAsyncClient in SQS integration tests
awspring/spring-cloud-aws pull request #727
Opened 2023-03-22 22:49 UTC by MikhailStrokov

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring

## :scroll: Description
For integration tests in SQS module, raw SqsAsyncClient client was substituted by SqsTemplate in methods for sending messages to queues.

## :bulb: Motivation and Context

Resolves awspring/spring-cloud-aws#658

When the integration tests for the SQS integration were created, SqsTemplate didn't exist.
Now it's necessary to change them so they use the template instead of the raw SqsAsyncClient.

## :green_heart: How did you test it?

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

2023-03-23 02:05 UTC, tomazfernandes requested changes
Thanks a lot for the PR @MikhailStrokov. Those `sendMessageTo` and `sendMessageBatch` were created to add functionality to the raw `SqsClient`, but shouldn't be necessary for `SqsTemplate`. Think you can replace those with equivalent from `SqsTemplate` and see if all tests remain green?

2023-03-24 00:56 UTC, tomazfernandes commented
> Hi @tomazfernandes, I have doubts about `io.awspring.cloud.sqs.integration.SqsFifoIntegrationTests#sendMessageTo`, so I want to clarify first. This method has logic based on `useLocalStackClient` flag. 

Yeah, this is because `LocalStack` implementation for `FIFO` queues is not reliable, so it needs to be sync to keep ordering. On the other hand some tests are also used to stress test against AWS, and for those cases async is better.

I think we can move the `if` statement on the `useLocalStackClient` flag to the `receivesMessagesInOrderFromManyMessageGroups` test, which is the one that cares about this the most, and just use the Template's blocking send methods on the other ones to help them pass on LocalStack.

We'd also need to have a `high throughput template` for that test in case we're targeting AWS.

How does that sound?

> Also, `sendMessageTo` and `sendMessageBatch` methods were removed from the others test classes.

Cool, thanks!

2023-03-25 09:48 UTC, MikhailStrokov commented
Hi @tomazfernandes, I've changed sending type to sync except `receivesMessagesInOrderFromManyMessageGroups`. I tried to get rid of `io.awspring.cloud.sqs.integration.SqsFifoIntegrationTests#doSendMessageTo` but it looked like a mess when I merged it into `io.awspring.cloud.sqs.integration.SqsFifoIntegrationTests#sendManyAsyncTo` method. So I left it as it is. Let me know what I can change to make it more clear or improve readability.

2023-03-26 15:37 UTC, tomazfernandes commented
> Hi @tomazfernandes, I've changed sending type to sync except `receivesMessagesInOrderFromManyMessageGroups`. I tried to get rid of `io.awspring.cloud.sqs.integration.SqsFifoIntegrationTests#doSendMessageTo` but it looked like a mess when I merged it into `io.awspring.cloud.sqs.integration.SqsFifoIntegrationTests#sendManyAsyncTo` method. So I left it as it is. Let me know what I can change to make it more clear or improve readability.

I think we should not need any of these `sendMessageTo` auxiliary methods, and should be able to rely on the `SqsTemplate` API directly instead in the test methods.

The one thing I'm aware that the API doesn't offer much help yet is to create multiple messages for `sendMany` methods. For these we should be able to maybe just use a `stream#map` to create the messages in the test method itself, or maybe have a method that takes the parameters and return `List<Message<>>`.

How does that sound?

Thanks

2023-04-19 01:40 UTC, tomazfernandes commented
@MikhailStrokov, thanks a lot for the PR!

We're releasing 3.0 GA soon, so I've added one commit with what was missing and since I couldn't push to your branch I opened a new PR.

I added your name to the test classes you changed, hope it's ok.

Thanks again!

Closed in favor of https://github.com/awspring/spring-cloud-aws/pull/770

2023-04-19 01:40 UTC, closed without merging