Fixes gh-697 Enhance SqsAutoConfiguration to use an available ObjectM…
awspring/spring-cloud-aws pull request #845
Opened 2023-07-10 07:53 UTC by mmaeller

## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
See https://github.com/awspring/spring-cloud-aws/discussions/697#discussioncomment-6368312

## :bulb: Motivation and Context
Please see https://github.com/awspring/spring-cloud-aws/discussions/697

## :green_heart: How did you test it?
See extended unit tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

2023-09-06 02:09 UTC, tomazfernandes requested changes
Sorry for the delay @mmaeller! Looks good, but there's an issue with the formatting that's creating lots of diffs.

Can you please fix that?

Thanks!

2023-09-06 02:09 UTC, tomazfernandes commented on spring-cloud-aws-autoconfigure/src/test/java/io/awspring/cloud/autoconfigure/sqs/SqsAutoConfigurationTest.java
> +					assertThat(options.getMessageConverter()).isInstanceOfSatisfying(
Same here, please let's try to simplify this a bit.

2023-10-05 16:24 UTC, postalservice14 commented
@tomazfernandes I made the requested changes in a new PR: https://github.com/awspring/spring-cloud-aws/pull/906 - I really would like this released and it seems the original author hasn't had time. :-)

2023-10-12 08:41 UTC, mmaeller commented
Hi @postalservice14, Thank you for the adjustments.
And sorry to @tomazfernandes, somehow the mails reached my spam folder :(

2023-10-12 08:41 UTC, closed without merging