Fixed the order of importing properties
awspring/spring-cloud-aws pull request #882
Opened 2023-09-12 17:43 UTC by tomek82

## :loudspeaker: Type of change

- [ x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Change the Secrets Manager resolver to use resolve instead of resolveProfileSpecific to fix the import order bug.

## :bulb: Motivation and Context

https://github.com/awspring/spring-cloud-aws/issues/881

## :green_heart: How did you test it?
Build locally and run application with 
`spring.config.import=aws-secretsmanager:${ENV}/config,optional:classpath:config.properties`
and verified that the properties are overridden correctly. Also tested with profile-specific application-local.properties.

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2023-10-23 12:43 UTC, maciejwalkowiak requested changes
Thanks @tomek82. Good catch. Can you add a test for this change?

2023-10-23 18:42 UTC, tomek82 commented
What is a good way to test it? My attempts with adding a classpath source to command line in io.awspring.cloud.autoconfigure.config.secretsmanager.SecretsManagerConfigDataLoaderIntegrationTests fail as it seems to be working without this change and I can't get a separate @PropertySource to work either (it does load the file but doesn't process the secrets import).

2023-10-30 06:19 UTC, maciejwalkowiak commented
You can test it like this.

Add test to `SecretsManagerConfigDataLoaderIntegrationTests`:

```
@Test
void respectsImportOrder() {
	SpringApplication application = new SpringApplication(App.class);
	application.setWebApplicationType(WebApplicationType.NONE);

	try (ConfigurableApplicationContext context = runApplication(application,
		"aws-secretsmanager:/config/spring,classpath:config.properties")) {
		assertThat(context.getEnvironment().getProperty("another-parameter")).isEqualTo("from properties file");
	}
}
```

and `config.properties` file in `src/test/resources`:

```properties
another-parameter=from properties file
```

The test passes without your changes too, so I am a bit puzzled. Perhaps this bug exists only in 2.x?

2023-10-30 18:06 UTC, tomek82 commented
I've added a test with one more level of indirection, without my fix this fails to load the properties in the right order.

2023-11-03 23:14 UTC, maciejwalkowiak approved these changes
Thanks! Because it may have surprising side effects we will release it with 3.1.0

2023-12-01 07:37 UTC, merged